### ISSUE TITLE
User Study

### ISSUE THREAD

**Issue by kaessmTS** [kaessmTS/TravelPlanner#2]
# TODO

- [x] get 10 participants (students, teachers, what ever)
- [x] note down their names, age (rounded in 10 years)
- [x] use the questionaire from the ppt
- [x] do a user study
- [x] !!!!!use a measurement to measure the significance between the tests like f1 or man-whitney test to evaluate the results

**Comment by coveetak88** [comment]
Here's the Survey Questionare! 
https://forms.gle/Sswdn5Xfoy7NeN9W6
