### ISSUE TITLE
PPT with the results

### ISSUE THREAD

**Issue by T0B1K** [kaessmTS/TravelPlanner#5]
#Create a PPT

- [x]  PPT with our usual design
## **Part 1** our app
- [x] "what our app looks like" maybe a demo (video)
## **Part 2**  user study

- [x]  Copy the user study design from the last slides

## **Part 3** Results

- [x] Present the results from the user study including the "mathematically measured results"

**Comment by coveetak88** [comment]
PPT Link: https://docs.google.com/presentation/d/1ouXLBwYL_nAj8-pU5WVhedY566GChwVl_N46l0mWIrg/edit?usp=sharing
Video Demo: https://drive.google.com/file/d/1dHi9uKGLlh_OwCz_tlWFPo9B-u3VIpjE/view?usp=sharing
